#:schema node_modules/wrangler/config-schema.json
name = "lora-gateway-worker"
main = "src/index.ts"
compatibility_date = "2024-03-08"

[[d1_databases]]
binding = "DB"
database_name = "lora-db"
database_id = "302410b6-2175-4d43-8a7b-a021273744a7"
